#!/bin/sh
#adding another comment in sandeepkumar-k-patch-1
#adding another comment in sandeepkumar-k-patch-1#adding another comment in sandeepkumar-k-patch-1

#learning
set -e

bundle exec jekyll build --baseurl "."
htmlproofer _site/index.html --empty-alt-ignore
